name: Check Code Style - Ruff
permissions:
  contents: read

on:
  push:
    branches: [main, humble]
  pull_request:
    branches: [main, humble]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
      - uses: astral-sh/ruff-action@eaf0ecdd668ceea36159ff9d91882c9795d89b49 # v3
      - name: Ruff Check
        run: ruff check --fix
      - name: Ruff Format
        run: ruff format
