name: Check Code Style - Ruff

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/ruff-action@v3
      - name: Ruff Check
        run: ruff check --fix
      - name: Ruff Format
        run: ruff format
